# Kibana is served by a back end server. This controls which port to use.
port: 5601

# The host to bind the server to.
host: "${SERVER_HOST:-0.0.0.0}"

# The Elasticsearch instance to use for all your queries.
elasticsearch_url: "${ELASTICSERACH_URL}"

# If your Elasticsearch is protected with basic auth, this is the user credentials
# used by the Kibana server to perform maintence on the kibana_index at statup. Your Kibana
# users will still need to authenticate with Elasticsearch (which is proxied thorugh
# the Kibana server)
kibana_elasticsearch_username: "${ELASTICSERACH_USERNAME}"
kibana_elasticsearch_password: "${ELASTICSERACH_PASSWORD}"

# preserve_elasticsearch_host true will send the hostname specified in `elasticsearch`. If you set it to false,
# then the host you use to connect to *this* Kibana instance will be sent.
elasticsearch_preserve_host: "${ELASTICSERACH_PRESERVEHOST:-true}"

# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create a new index if it doesn't already exist.
kibana_index: "${KIBANA_INDEX:-.kibana}"

# The default application to load.
default_app_id: "${KIBANA_DEFAULTAPPID:-discover}"

# If your Elasticsearch is protected with basic auth, this is the user credentials
# used by the Kibana server to perform maintence on the kibana_index at statup. Your Kibana
# users will still need to authenticate with Elasticsearch (which is proxied thorugh
# the Kibana server)
# elasticsearch.username: user
# elasticsearch.password: pass

# Time in milliseconds to wait for elasticsearch to respond to pings, defaults to
# request_timeout setting
ping_timeout: ${ELASTICSEARCH_PINGTIMEOUT:-1500}

# Time in milliseconds to wait for responses from the back end or elasticsearch.
# This must be > 0
request_timeout: ${ELASTICSEARCH_REQUESTTIMEOUT:-300000}

# Time in milliseconds for Elasticsearch to wait for responses from shards.
# Set to 0 to disable.
shard_timeout: ${ELASTICSEARCH_SHARDTIMEOUT:-0}

# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying
startup_timeout: ${ELASTICSEARCH_STARTUPTIMEOUT:-5000}

# SSL for outgoing requests from the Kibana Server (PEM formatted)
# server.ssl.cert: /path/to/your/server.key
# server.ssl.key: /path/to/your/server.crt

# Plugins that are included in the build, and no longer found in the plugins/ folder
bundled_plugin_ids:
 - plugins/dashboard/index
 - plugins/discover/index
 - plugins/doc/index
 - plugins/kibana/index
 - plugins/markdown_vis/index
 - plugins/metric_vis/index
 - plugins/settings/index
 - plugins/table_vis/index
 - plugins/vis_types/index
 - plugins/visualize/index
